[features]
seeds = false
skip-lint = false

[programs.localnet]
memecoin_lending = "MCLend1111111111111111111111111111111111111"

[programs.devnet]
memecoin_lending = "MCLend1111111111111111111111111111111111111"

[programs.mainnet]
memecoin_lending = "MCLend1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"