[package]
name = "memecoin-lending"
version = "0.1.0"
description = "Memecoin lending protocol on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "memecoin_lending"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
arrayref = "0.3.6"
solana-program = "1.18.11"
solana-client = "1.18.11"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "2.3.0", features = ["no-entrypoint"] }
pyth-solana-receiver-sdk = "0.2.2"

[dev-dependencies]
solana-sdk = "1.18.11"
solana-program-test = "1.18.11"